//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheFuZi.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_Category
    {
        public int CateId { get; set; }
        public int ParentId { get; set; }
        public string CateTitle { get; set; }
        public string CateImage { get; set; }
        public string Description { get; set; }
        public System.DateTime AddDate { get; set; }
        public int OrderBy { get; set; }
        public int Status { get; set; }
    }
}
