//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheFuZi.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public long ArticlId { get; set; }
        public int CateId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleAuthor { get; set; }
        public Nullable<System.DateTime> ArticleDate { get; set; }
        public string Reference { get; set; }
        public string ArticleSummary { get; set; }
        public string ArticleContent { get; set; }
        public string ArticleImages { get; set; }
        public string ArticleVideo { get; set; }
        public System.DateTime AddDate { get; set; }
        public int ReadTimes { get; set; }
        public Nullable<int> CommentCount { get; set; }
        public int PraiseCount { get; set; }
        public int OrderBy { get; set; }
        public int Status { get; set; }
    }
}
