//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheFuZi.DataBaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chefuzi_dataEntities : DbContext
    {
        public chefuzi_dataEntities()
            : base("name=chefuzi_dataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Article_Category> Article_Category { get; set; }
        public virtual DbSet<Article_Comment> Article_Comment { get; set; }
        public virtual DbSet<Sys_Area_City> Sys_Area_City { get; set; }
        public virtual DbSet<Sys_Area_District> Sys_Area_District { get; set; }
        public virtual DbSet<Sys_Area_Province> Sys_Area_Province { get; set; }
        public virtual DbSet<Sys_IdKey> Sys_IdKey { get; set; }
        public virtual DbSet<Sys_IdTable> Sys_IdTable { get; set; }
        public virtual DbSet<Sys_Status> Sys_Status { get; set; }
        public virtual DbSet<Sys_Suggestion> Sys_Suggestion { get; set; }
        public virtual DbSet<User_Collect> User_Collect { get; set; }
        public virtual DbSet<User_LoginCategory> User_LoginCategory { get; set; }
        public virtual DbSet<User_PhoneCheckCode> User_PhoneCheckCode { get; set; }
        public virtual DbSet<User_Roles> User_Roles { get; set; }
        public virtual DbSet<User_UserInfo> User_UserInfo { get; set; }
        public virtual DbSet<User_UserLogin> User_UserLogin { get; set; }
        public virtual DbSet<User_UserName> User_UserName { get; set; }
    }
}
