//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheFuZi.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_PhoneCheckCode
    {
        public string MobilePhone { get; set; }
        public string CheckCode { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<bool> AlreadCheck { get; set; }
    }
}
