//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheFuZi.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_UserInfo
    {
        public long UserId { get; set; }
        public string Email { get; set; }
        public string PassWord { get; set; }
        public string RealName { get; set; }
        public bool Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string HeadImage { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<int> CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string DistrictName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public int Status { get; set; }
    }
}
