//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheFuZi.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Collect
    {
        public long CollectId { get; set; }
        public long UserId { get; set; }
        public long AboutId { get; set; }
        public string AboutTitle { get; set; }
        public System.DateTime CollectDate { get; set; }
        public Nullable<long> OrderBy { get; set; }
    }
}
